FROM projectatomic/atomicapp:0.1.12

MAINTAINER Jeroen van Meeuwen <vanmeeuwen@kolabsys.com>

LABEL io.projectatomic.nulecule.specversion="0.0.2" \
      io.projectatomic.nulecule.providers="docker,kubernetes,openshift"

ADD /Nulecule /Dockerfile /application-entity/
ADD /artifacts /application-entity/artifacts/
