FROM projectatomic/atomicapp:0.1.12

MAINTAINER Kolab Systems <contact@kolabsys.com>

LABEL io.projectatomic.nulecule.providers="kubernetes" \
      io.projectatomic.nulecule.specversion="0.0.2"

ADD /Nulecule /Dockerfile /application-entity/
